// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9BEgYJuT9y1hGWi5RVDoxQQVDZIT7nNE',
    appId: '1:502653964510:web:74689ee6fe9d336bf8324f',
    messagingSenderId: '502653964510',
    projectId: 'fooddeliveryapp-d7c41',
    authDomain: 'fooddeliveryapp-d7c41.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-d7c41.appspot.com',
    measurementId: 'G-3RM8K07140',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPkru5ShdoSEkXH_RE6gAlO_MKo97--LM',
    appId: '1:502653964510:android:4f251318f2148324f8324f',
    messagingSenderId: '502653964510',
    projectId: 'fooddeliveryapp-d7c41',
    storageBucket: 'fooddeliveryapp-d7c41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZUePSN8ZzJQRpffVT0obmCFniCoAwDU',
    appId: '1:502653964510:ios:d58fd0ce944ab46af8324f',
    messagingSenderId: '502653964510',
    projectId: 'fooddeliveryapp-d7c41',
    storageBucket: 'fooddeliveryapp-d7c41.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ZUePSN8ZzJQRpffVT0obmCFniCoAwDU',
    appId: '1:502653964510:ios:1fe89650db676d09f8324f',
    messagingSenderId: '502653964510',
    projectId: 'fooddeliveryapp-d7c41',
    storageBucket: 'fooddeliveryapp-d7c41.appspot.com',
    iosBundleId: 'com.example.food.RunnerTests',
  );
}
